// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWktxLkffbLnmtZsz43KP4IfeT_bVm_0',
    appId: '1:175741921267:web:b9d5480add64e4ab375486',
    messagingSenderId: '175741921267',
    projectId: 'waterapp-403ac',
    authDomain: 'waterapp-403ac.firebaseapp.com',
    databaseURL: 'https://waterapp-403ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterapp-403ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIvMJ_asd3mvhRx2NFv373Yki0vrFQghU',
    appId: '1:175741921267:android:96c627c8d190c530375486',
    messagingSenderId: '175741921267',
    projectId: 'waterapp-403ac',
    databaseURL: 'https://waterapp-403ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterapp-403ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwpOO9s1Q3bxf0BS_Tw8INRHUa8-9rps',
    appId: '1:175741921267:ios:7fa9467ebba122bf375486',
    messagingSenderId: '175741921267',
    projectId: 'waterapp-403ac',
    databaseURL: 'https://waterapp-403ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterapp-403ac.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLwpOO9s1Q3bxf0BS_Tw8INRHUa8-9rps',
    appId: '1:175741921267:ios:02d236d88e1dbe6b375486',
    messagingSenderId: '175741921267',
    projectId: 'waterapp-403ac',
    databaseURL: 'https://waterapp-403ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterapp-403ac.appspot.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
